name: QuizLITE Automated Tests

on: [push, pull_request]

jobs:
  build-ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      matrix:
        name: [Clang, GCC]

        include:
          - name: Clang
            cc: clang
            cxx: clang++

          - name: GCC
            cc: gcc
            cxx: g++

    steps:
      - name: Clone repository
        uses: actions/checkout@master
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} ..
      - name: Build
        run: cmake --build build
      - name: Run test cases
        run: |
          cd bin
          ./testing

  build-macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew update
          brew install cmake sqlite3
          brew install googletest

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: |
          cd build
          ctest

  linter:
    name: Linter
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@master
      - name: Run linter
        uses: DoozyX/clang-format-lint-action@v0.8
        with:
          source: 'Database User tests'
          extensions: 'cpp,h'
          style: webkit
